version: '3.8'

services:
  # 1. Container Antrean Redis Lokal
  redis-queue:
    image: redis:7-alpine
    container_name: auditchain-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - gateway-net

  # 2. Container Aplikasi Go (Gateway)
  api-gateway:
    build: .
    container_name: auditchain-api
    ports:
      - "3000:3000"
    depends_on:
      - redis-queue
    environment:
      - REDIS_HOST=redis-queue:6379
      - REDIS_PASSWORD=
    networks:
      - gateway-net
      - fabric-net     # Terhubung ke Blockchain Fabric

volumes:
  redis-data:

networks:
  gateway-net:
    driver: bridge
  fabric-net:
    external: true     
    name: fabric_test  # 👈 Menggunakan network Fabric dari PC Lab